name: workouts
description: A new Flutter project.

publish_to: 'none'
version: 0.4.0+3

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  http: ^1.2.2
  sqflite: ^2.4.0
  flutter_secure_storage: ^9.2.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^7.7.0
  go_router: ^14.3.0
  shared_preferences: ^2.1.1
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  meta: ^1.15.0
  intl: ^0.18.1

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

